server:
  port: 8200

spring:
  application:
    name: jiangjf-order-api

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7000/eureka

feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000