server:
  port: 7000
spring:
  application:
    name: jiangjf-eureka

eureka:
  instance:
    hostname: jiangjf-eureka
  client:
    service-url:
      defaultZone: http://127.0.0.1:7000/eureka
    register-with-eureka: false
    fetch-registry: false